#DGS configuration refer :https://netflix.github.io/dgs/configuration/

spring:
  application:
    name: netflix-dgs-graphql-example
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true


jsonplaceholder:
  url: http://localhost:1080



#Enable custom exception handler
exception:
  custom:
    enable: false


#DGS Extended Scalars: graphql-dgs-extended-scalars¶
dgs:
  graphql:
    extensions:
      scalars:
        time-dates:
          enabled: true