#DGS configuration refer :https://netflix.github.io/dgs/configuration/

spring:
  application:
    name: netflix-dgs-graphql-example
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true


jsonplaceholder:
  url: http://localhost:1080



#Enable custom exception handler
exception:
  custom:
    enable: true


#DGS Extended Scalars: graphql-dgs-extended-scalars¶
dgs:
  graphql:
    extensions:
      scalars:
        time-dates:
          enabled: true
voyager:
  enabled: true
  basePath: /
  mapping: /voyager
  endpoint: /graphql
  cdn:
    enabled: false
    version: latest
  pageTitle: Voyager
  displayOptions:
    skipRelay: true
    skipDeprecated: true
    rootType: Query
    sortByAlphabet: false
    showLeafFields: true
    hideRoot: false
  hideDocs: false
  hideSettings: false

graphql:
  servlet:
  playground:
    tabs:
      - name: Book sample query
        query: classpath:playground/book-query.graphql
        variables: classpath:playground/book-query-variable.json
      - name: JsonPlace holder sample query
        query: classpath:playground/jsonplaceholder-query.graphql

    cdn:
      enabled: true